openapi: "3.0.3"
# openapi: "3.0.0"
info:
  description: 首都圏の公開された新型コロナ情報を取得できるAPI
  version: "1.0"
  title: コロナRestAPI
  termsOfService: http://xxxxxx.com
  contact:
    name: Poon Ying Wai
    url: http://xxxx.xx
    email: han@email.com
  license:
    name: my license
    url: http://xxxlicense__xx.com
servers:
  - url: http://localhost/corona
    description: Development server
    variables:
      port:
        enum:
          - '5000'
#          - '80'
        default: '5000'
      basePath:
        default: corona

paths:
  /1.0/number/patients_list:
    get:
      operationId: "corona.get_patients_list"
      tags:
        - patients_number
      summary: 公開された地域の感染者情報の一覧を取得する
      description: JSONデータ構造になります。
      parameters:
        - name: area
          in: query
          required: true
          schema:
            type: string
          description: データ取得対象の地域名（都道府県・市など）
        - name: address
          in: query
          required: true
          schema:
            type: string
          description: 更に詳しい地域名。部分マッチング可能
        - name: start_date
          in: query
          required: true
          schema:
            type: string
          description: 開始日 (yyyy-mm-dd)
        - name: end_date
          in: query
          required: true
          schema:
            type: string
          description: 終了日 (yyyy-mm-dd)
        - name: option_keys
          in: query
          schema:
            type: array
            items:
              type: string
          required: false
          description: 追加指定条件のキー（複数可）
        - name: option_values
          in: query
          schema:
            type: array
            items:
              type: string
          description: option_keysに対応する値（複数可）
        - name: offset
          in: query
          schema:
            type: integer
            format: int32
          required: false
          description: 指定した値の個数のデータから取得する
        - name: limit
          in: query
          schema:
            type: integer
            format: int32
          required: false
          description: データの取得個数を制限する
        - name: forced
          in: query
          schema:
            type: boolean
          required: false
          description: データ強制更新 ＃POSTメソッドで対応予定
      responses:
        200:
          description: 結果が正常に取得できました
        500:
          description: サーバ内部がエラーになります。

  /1.0/number/patients_number:
    get:
      operationId: "corona.get_numbers"
      tags:
        - patients_number
      summary: 感染者数取得
      description: 指定した条件でその日または一定期間内の感染者数を取得
      parameters:
        - name: area
          in: query
          schema:
            type: string
          required: true
          description: データ取得対象の地域名（都道府県・市など）
        - name: start_date
          in: query
          schema:
            type: string
          required: true
          description: 開始日 (yyyy-mm-dd)
        - name: end_date
          in: query
          schema:
            type: string
          required: true
          description: 終了日 (yyyy-mm-dd)
        - name: address
          in: query
          schema:
            type: string
          required: false
          description: 更に詳しい地域名。部分マッチング可能
        - name: forced
          in: query
          schema:
            type: boolean
          required: false
          description: データ強制更新  ＃POSTメソッドで対応予定
      responses:
        200:
          description: 感染者数の正常に取得できました
        500:
          description: サーバ内部がエラーになります。

# DataFrameを更新するAPIが必要です。
  /1.0/number/options:
    get:
      operationId: "corona.get_options"
      tags:
        - patients_number
      summary: 提供された感染情報テーブルの列情報を取得
      description: 各地域・市などから公開された情報は差分があり、このAPIで指定された地域の取得可能な情報を問い合わせできます
      parameters:
        - name: area
          in: query
          schema:
            type: string
          required: true
          description: データ取得対象の地域名（都道府県・市など）
        - name: address
          in: query
          schema:
            type: string
          required: true
          description: 更に詳しい地域名。部分マッチング可能
        - name: start_date
          in: query
          schema:
            type: string
          required: true
          description: 開始日 (yyyy-mm-dd)
        - name: end_date
          in: query
          schema:
            type: string
          required: true
          description: 終了日 (yyyy-mm-dd)
        - name: forced
          in: query
          schema:
            type: boolean
          required: false
          description: データ強制更新  ＃POSTメソッドで対応予定
      responses:
        200:
          description: good
        500:
          description: bad
